-- ============================================================
-- V1 初始 schema
--
-- 型別刻意只用 PostgreSQL 與 H2 都支援的標準寫法
-- （BIGINT GENERATED BY DEFAULT AS IDENTITY、DECIMAL、TIMESTAMP），
-- 這樣同一份 migration 在正式環境與無 Docker 的開發機都能跑，
-- 測試驗證過的 schema 才等於正式環境的 schema。
-- ============================================================

-- ---------- 使用者 ----------
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(50)  NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    line_code     VARCHAR(20),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    created_by    VARCHAR(50),
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(50),
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

-- ---------- 物料主檔 ----------
CREATE TABLE material (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code VARCHAR(30)    NOT NULL,
    material_name VARCHAR(100)   NOT NULL,
    unit          VARCHAR(10)    NOT NULL,
    safety_stock  DECIMAL(18, 4) NOT NULL DEFAULT 0,
    created_at    TIMESTAMP      NOT NULL,
    created_by    VARCHAR(50),
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(50),
    CONSTRAINT uk_material_code UNIQUE (material_code)
);

-- ---------- 用料表（單階 BOM） ----------
CREATE TABLE bom_item (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code  VARCHAR(30)    NOT NULL,
    material_code VARCHAR(30)    NOT NULL,
    qty_per_unit  DECIMAL(18, 4) NOT NULL,
    scrap_rate    DECIMAL(6, 4)  NOT NULL DEFAULT 0,
    created_at    TIMESTAMP      NOT NULL,
    created_by    VARCHAR(50),
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(50),
    CONSTRAINT uk_bom_product_material UNIQUE (product_code, material_code),
    CONSTRAINT ck_bom_qty_positive CHECK (qty_per_unit > 0)
);

-- ---------- 庫存 ----------
CREATE TABLE inventory (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code  VARCHAR(30)    NOT NULL,
    warehouse_code VARCHAR(20)    NOT NULL,
    qty_on_hand    DECIMAL(18, 4) NOT NULL DEFAULT 0,
    version        BIGINT         NOT NULL DEFAULT 0,
    created_at     TIMESTAMP      NOT NULL,
    created_by     VARCHAR(50),
    updated_at     TIMESTAMP,
    updated_by     VARCHAR(50),
    CONSTRAINT uk_inventory_material_wh UNIQUE (material_code, warehouse_code),
    -- 資料庫層再擋一次負庫存：即使日後有人寫了繞過 Entity 的更新語句，帳也不會變成負的
    CONSTRAINT ck_inventory_non_negative CHECK (qty_on_hand >= 0)
);

-- ---------- 工單 ----------
CREATE TABLE work_order (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no      VARCHAR(30)  NOT NULL,
    product_code  VARCHAR(30)  NOT NULL,
    product_name  VARCHAR(100) NOT NULL,
    planned_qty   INTEGER      NOT NULL,
    produced_qty  INTEGER      NOT NULL DEFAULT 0,
    defect_qty    INTEGER      NOT NULL DEFAULT 0,
    status        VARCHAR(20)  NOT NULL,
    line_code     VARCHAR(20)  NOT NULL,
    planned_start TIMESTAMP    NOT NULL,
    planned_end   TIMESTAMP    NOT NULL,
    actual_start  TIMESTAMP,
    actual_end    TIMESTAMP,
    status_remark VARCHAR(200),
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL,
    created_by    VARCHAR(50),
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(50),
    CONSTRAINT uk_work_order_no UNIQUE (order_no),
    CONSTRAINT ck_wo_planned_qty_positive CHECK (planned_qty > 0),
    CONSTRAINT ck_wo_qty_non_negative CHECK (produced_qty >= 0 AND defect_qty >= 0)
);

CREATE INDEX idx_wo_status_line ON work_order (status, line_code);
CREATE INDEX idx_wo_planned_start ON work_order (planned_start);

-- ---------- 報工紀錄 ----------
CREATE TABLE production_report (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id   BIGINT      NOT NULL,
    order_no        VARCHAR(30) NOT NULL,
    line_code       VARCHAR(20) NOT NULL,
    operator        VARCHAR(50) NOT NULL,
    machine_code    VARCHAR(20),
    good_qty        INTEGER     NOT NULL,
    defect_qty      INTEGER     NOT NULL,
    defect_reason   VARCHAR(50),
    work_minutes    INTEGER     NOT NULL DEFAULT 0,
    reported_at     TIMESTAMP   NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    created_at      TIMESTAMP   NOT NULL,
    created_by      VARCHAR(50),
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(50),
    -- 防重複扣料的最後防線。應用層的「先查再寫」在多節點併發下會漏，這條不會。
    CONSTRAINT uk_report_idempotency UNIQUE (idempotency_key),
    CONSTRAINT fk_report_work_order FOREIGN KEY (work_order_id) REFERENCES work_order (id),
    CONSTRAINT ck_report_qty_non_negative CHECK (good_qty >= 0 AND defect_qty >= 0)
);

CREATE INDEX idx_report_work_order ON production_report (work_order_id);
CREATE INDEX idx_report_reported_at ON production_report (reported_at);
-- 日結與報表都以「產線 + 日期」為條件，複合索引讓它們免掃全表
CREATE INDEX idx_report_line_date ON production_report (line_code, reported_at);

-- ---------- 物料異動流水 ----------
CREATE TABLE material_transaction (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code  VARCHAR(30)    NOT NULL,
    warehouse_code VARCHAR(20)    NOT NULL,
    qty            DECIMAL(18, 4) NOT NULL,
    tx_type        VARCHAR(20)    NOT NULL,
    work_order_id  BIGINT,
    report_id      BIGINT,
    balance_after  DECIMAL(18, 4) NOT NULL,
    created_at     TIMESTAMP      NOT NULL,
    created_by     VARCHAR(50),
    updated_at     TIMESTAMP,
    updated_by     VARCHAR(50)
);

CREATE INDEX idx_mtx_material ON material_transaction (material_code, created_at);
CREATE INDEX idx_mtx_work_order ON material_transaction (work_order_id);

-- ---------- 日結彙總 ----------
CREATE TABLE daily_production_summary (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary_date       DATE          NOT NULL,
    line_code          VARCHAR(20)   NOT NULL,
    total_good_qty     INTEGER       NOT NULL DEFAULT 0,
    total_defect_qty   INTEGER       NOT NULL DEFAULT 0,
    total_work_minutes INTEGER       NOT NULL DEFAULT 0,
    defect_rate        DECIMAL(6, 4) NOT NULL DEFAULT 0,
    utilization_rate   DECIMAL(6, 4) NOT NULL DEFAULT 0,
    report_count       INTEGER       NOT NULL DEFAULT 0,
    created_at         TIMESTAMP     NOT NULL,
    created_by         VARCHAR(50),
    updated_at         TIMESTAMP,
    updated_by         VARCHAR(50),
    -- 讓日結批次可以重跑：同一天同一產線只會有一筆
    CONSTRAINT uk_summary_date_line UNIQUE (summary_date, line_code)
);
